pipeline{
    agent none
    stages{
        stage('one'){
            steps{
                echo "This is from stage one"
            }
        }
        stage('Two'){
            steps{
                echo "This is from stage Two"
            }
        }
        stage('Three'){
            steps{
                echo "This is from stage Three"
            }
        }
        stage('Four'){
            steps{
                echo "This is from stage Four"
            }
        }

    }
    post {
        always{
            echo "This run always"
        }
        success{
            echo "This only runs when pipeline succeeded"
        }
    }
}