pipeline {
    agent any

    environment {
        ENV_TYPE = 'prod'
    }

    tools{
        java 'jdk-17'
    }

    stages {

        stage('Build') {
            steps {
                echo "I am from stage one"
            }
        }

        stage('Approval') {
            agent none
            steps {
                input message: "Do you want to approve this build?"
                    
            }
        }

        stage('Deploy') {
            when {
                environment name: 'ENV_TYPE', value: 'prod'
            }
            steps {
                echo "Deploying to production"
            }
        }
    }
}