apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    env: dev
spec:
  containers:
  - name: nginx
    image: nginx
  - name: nginx1
    image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: newservice
spec:
  selector:
    env: dev
  ports:
  - name: newservice
    protocol: "TCP"
    port: 80
    targetPort: 80