apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: sets 
spec:
 replicas: 3
 selector:
  matchLabeles:
    app: dev
 template:
  metadata:
    name: nginx
    labels:
     app: dev
  spec:
    containers:
    - name: nginx
      image: nginx
