apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
       cpu: 120mi
       memory: 120mi
      limits:
       cpu: 120mi
       memory: 120mi