apiVersion: apps/v1
kind: Deployment
metadata:
  name: sets 
spec:
 replicas: 3
 selector:
  matchLabels:
    app: dev
 template:
  metadata:
    name: nginx
    labels:
     app: dev
  spec:
    containers:
    - name: nginx
      image: nginx
