- name: To enable nginx conditionally
  hosts: web
  become: yes
  tasks: 
  - name: To install nginx
    package:
     name: nginx
     state: present
    when: ansible_facts['distribution'] == 'Amazon Linux'
  - name: To starte nginx
    service:
     name: nginx
     state: started
  - name: To change config vars_files
    copy:
     content: "hello"
     dest: "/home/ece-user"
    notify: restart nginx
  handlers:
  - name: restart nginx
    service:
     name: nginx
     state: started
     enabled: yes