- name: Enable nginx conditionally
  hosts: web
  become: yes

  tasks:

    - name: Install multiple packages
      package:
        name: "{{ item }}"
        state: present
      register: pkg_result
      when: ansible_distribution == "Amazon"
      loop:
      - nginx
      - git
      - curl

    - name: Start nginx
      service:
        name: nginx
        state: started
      when: ansible_distribution == "Amazon"

    - name: Change config
      copy:
        content: "hello"
        dest: "/etc/nginx/test.conf"
      notify: restart nginx
      when: ansible_distribution == "Amazon"

  handlers:

    - name: restart nginx
      service:
        name: nginx
        state: restarted