- name: Enable nginx conditionally
  hosts: web
  become: yes

  tasks:

    - name: Install nginx
      package:
        name: nginx
        state: present
      when: ansible_distribution == "Amazon"

    - name: Start nginx
      service:
        name: nginx
        state: started
      when: ansible_distribution == "Amazon"

    - name: Change config
      copy:
        content: "hello"
        dest: "/etc/nginx/test.conf"
      notify: restart nginx
      when: ansible_distribution == "Amazon"

  handlers:

    - name: restart nginx
      service:
        name: nginx
        state: restarted